In [1]:
import sys
sys.path.append("../../src")
import numpy as np
import matplotlib.pyplot as plt
from IPython import display
import pylab as pl

from general_utils import *
from bss_utils import *
from dsp_utils import *
from polytope_utils import *
from tqdm import tqdm

import warnings

warnings.filterwarnings("ignore")

notebook_name = "Polytope Plotting"

In [2]:
dim = 3
signed_dims = np.array([0, 1, 2])
nn_dims = np.array([])
sparse_dims_list = []
(A, b), V = generate_practical_polytope(dim, signed_dims, nn_dims, sparse_dims_list)

In [3]:
np.linalg.norm(A @ V - b[:, np.newaxis] > 0)

0.0

In [4]:
A, b = pypoman.compute_polytope_halfspaces(V.T)

In [5]:
y = np.array([-2, 1.1, 0.3])
ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), True)

Optimization terminated successfully


array([-1. ,  1. ,  0.3])

In [6]:
dim = 6
signed_dims = np.array([0, 1, 2, 5])
nn_dims = np.array([3, 4])
sparse_dims_list = [np.array([0, 1, 2]), np.array([2, 4, 5])]
(A, b), V = generate_practical_polytope(dim, signed_dims, nn_dims, sparse_dims_list)

y = np.array([-1.5, 2, 0.4, 3, -2, 0.01])
y_projected1 = ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), True)
y_projected2 = ProjectOntoPolytopeCanonical(y, A, b, V.mean(axis = 1), True)
y_projected1, y_projected2

Optimization terminated successfully
Optimization terminated successfully


(array([-2.50000000e-01,  7.50000000e-01,  2.77555756e-16,  1.00000000e+00,
         0.00000000e+00,  1.00000000e-02]),
 array([-2.50000000e-01,  7.50000000e-01,  2.77555756e-16,  1.00000000e+00,
         1.11022302e-16,  1.00000000e-02]))

In [7]:
dim = 15
signed_dims = np.arange(15)
nn_dims = np.array([])
sparse_dims_list = []
(A, b), V = generate_practical_polytope(dim, signed_dims, nn_dims, sparse_dims_list)
y = np.random.randn(15)
y_projected = ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), True)

Optimization terminated successfully


In [8]:
y, y_projected

(array([-1.63284271e+00, -1.17112962e+00,  1.83293201e+00, -2.52566474e-01,
         1.33067982e-03,  3.95740808e-01, -2.91967815e-01,  4.13591205e-01,
        -1.04220156e+00,  1.21235009e+00,  5.93987709e-01, -3.28564599e-01,
         9.26309359e-01, -1.64775894e+00, -1.81924594e+00]),
 array([-1.        , -1.        ,  1.        , -0.25256647,  0.00133068,
         0.39574081, -0.29196782,  0.41359121, -1.        ,  1.        ,
         0.59398771, -0.3285646 ,  0.92630936, -1.        , -1.        ]))

In [9]:
%timeit ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), False)

305 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
dim = 16
signed_dims = np.array([])
nn_dims = np.arange(16)
sparse_dims_list = []
(A, b), V = generate_practical_polytope(dim, signed_dims, nn_dims, sparse_dims_list)
A.shape

(32, 16)

In [11]:
y = np.random.randn(16)
y_projected = ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), True)

Optimization terminated successfully


In [12]:
y, y_projected

(array([-0.25513977, -0.86360216, -0.88786756,  0.10561846, -1.172492  ,
        -0.40750511,  0.87739413,  0.8102965 , -0.74082269,  0.77862019,
         2.9026437 , -0.46975041, -1.19815215,  0.26198447,  2.2828798 ,
         0.56132781]),
 array([ 8.88178420e-16, -2.10942375e-15, -2.88657986e-15,  1.05618462e-01,
        -2.88657986e-15, -1.05471187e-15,  8.77394134e-01,  8.10296504e-01,
        -1.77635684e-15,  7.78620190e-01,  1.00000000e+00, -8.88178420e-16,
        -2.88657986e-15,  2.61984469e-01,  1.00000000e+00,  5.61327814e-01]))

In [13]:
%timeit ProjectOntoPolytopeCanonical(y, A, b, np.zeros(y.shape[0]), False)

329 µs ± 25.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
